### ISSUE TITLE
Chat with Apple to check if they are still testing Firefox with new versions

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman-PostMortems#17]
Chat with Apple to check if they are still testing Firefox with new versions

**Comment by thomaselin** [comment]
Any update here @rvandermeulen ?

**Comment by rvandermeulen** [comment]
From our Apple contact:

> We don’t exhaustively test. It’s more like, launch, visit a site, print, quit without crashing. 
> We will also do specific ad hoc testing to cover something specific — an API deprecation or fixing something that affects a lot of developers, or security. When issues bubble up through the various ad hoc efforts, many of the teams know to come to me to reach out to you.
