### ISSUE TITLE
Evaluate Maire’s proposition: evaluate if we could push release updates to a target audience

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman-PostMortems#18]
Evaluate Maire’s proposition: evaluate if we could push release updates to a target audience
Assigned to Mihai/Sylvestre

**Comment by thomaselin** [comment]
Any update on this?

**Comment by sylvestre** [comment]
Seems that we could do it but we don't know if this is worse the effort.
if we want, we need to add it to the roadmap
