### ISSUE TITLE
Autonag: Add comment to ticket if patch lands on already fixed status

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman-PostMortems#21]
Autonag: Add comment to ticket if patch lands on already fixed status (assign to Marco)

**Comment by marco-c** [comment]
Should we act when the bug is RESOLVED FIXED and there is a new patch, or when the bug has "fixed" status flags and there is a new patch, or both?

Should we needinfo someone or just comment?

**Comment by marco-c** [comment]
A comment saying that the patch shouldn't have landed on a closed bug? Any suggested wording?
What is the goal exactly if we just add a comment? Teaching people not to do it next time?

**Comment by dsmithpadilla** [comment]
A comment suggesting this patch shouldn't have landed on this closed bug. The goal is to discourage the behavior but also to ensure there is visibility on the bug if further action is needed (like an uplift). 

Something **_like_** this "A patch has been landed on this ticket, but it has already been closed. Filing a separate ticket will ensure better tracking. If this was not by mistake and further action is needed, please alert the appropriate party."

**Comment by marco-c** [comment]
> A comment suggesting this patch shouldn't have landed on this closed bug. The goal is to discourage the behavior but also to ensure there is visibility on the bug if further action is needed (like an uplift).

Do we want also an email notification to release managers so you can notice these cases?

> Something **_like_** this "A patch has been landed on this ticket, but it has already been closed. Filing a separate ticket will ensure better tracking. If this was not by mistake and further action is needed, please alert the appropriate party."

:+1:

**Comment by dsmithpadilla** [comment]
yes that would be helpful if it is not too much trouble

**Comment by marco-c** [comment]
Perfect, we have a plan. I have filed https://github.com/mozilla/relman-auto-nag/issues/1318.
