### ISSUE TITLE
Evaluate if we could have autonag or Bugzilla to enforce severity requirements for a11y

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman-PostMortems#4]
A11y bugs caused by  new features
Action: Evaluate if we could have autonag or Bugzilla to enforce severity requirements => Marco, glob

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1742428

**Comment by marco-c** [comment]
An alternative to automatically changing the severity is https://github.com/mozilla/relman-auto-nag/issues/1290.

**Comment by globau** [comment]
I spoke with a11y and Marco about this, the preferred route is to needinfo the triage owner as per the issue Marco referenced.

Closing as the evaluation part is done; waiting for engineering.

**Comment by marco-c** [comment]
The new autonag script will land likely today or tomorrow, so this is basically all done now.
