### ISSUE TITLE
pref-flip should be a trigger for QA request

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman-PostMortems#5]
Platform work creating webcompat issues:
Action: pref-flip should be a trigger for QA request

**Comment by marco-c** [comment]
Were you planning to do this automatically?

**Comment by thomaselin** [comment]
What's the status on this? If we setup a notification for landed pref-flips can I please be added to that notification list?

**Comment by dsmithpadilla** [comment]
I think there wasnt an intention to automatically set this, just to inform QA when it happens, closing for now.
