### ISSUE TITLE
Evaluate how version numbers are parsed and reject invalid ones

### ISSUE THREAD

**Issue by dsmithpadilla** [mozilla/Relman-PostMortems#9]
AMO looking at how they’re parsing version numbers, possibly reject invalid ones: https://github.com/mozilla/addons/issues/1264

**Comment by rvandermeulen** [comment]
Discussion about how to handle this is covered in https://mozilla-hub.atlassian.net/browse/FIDE-620 and the linked summary doc. This falls under longer-term planning on the addons side of things and doesn't seem like something we need to track here at this point.
